<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class CatalogItem extends Model
{
    use HasFactory;
    protected $guarded = [];
    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->id = (string) Str::uuid();
        });
    }

    public function catalogable()
    {
        return $this->morphTo();
    }

    public function catalog()
    {
        return $this->belongsTo(Catalog::class);
    }
}
