<?php

namespace App\Models;

use App\Notifications\RequestRegister;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];
    public $incrementing = false;


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->id = (string) Str::uuid();
        });

        static::created(function ($user){
            // Logique à exécuter après l'insertion du modèle

            $user->notify(new RequestRegister($user));
        });
    }

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function wishlist()
    {
        return $this->hasOne(Wishlist::class);
    }

    public function catalog()
    {
        return $this->hasOne(Catalog::class);
    }

    public function cart()
    {
        return $this->hasOne(Cart::class);
    }

    public function toggleFavorite($articleId)
    {
        if ($this->favorites()->where('article_id', $articleId)->exists()) {
            $this->favorites()->where('article_id', $articleId)->delete();
            return 'removed';
        } else {
            $this->favorites()->create(['id' => (string) Str::uuid(), 'article_id' => $articleId]);
            return 'added';
        }
    }
}
