<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Wishlist extends Model
{
    use HasFactory;
    public $incrementing = false;
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->id = (string) Str::uuid();
        });
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function items()
    {
        return $this->hasMany(wishlist_item::class);
    }

    // Méthode pour calculer le montant total de la wishlist
    public function getCalculateTotalAmountAttribute()
    {
        $totalAmount = 0;

        // Parcourir chaque élément de la wishlist
        foreach ($this->items as $item) {
            // Vérifier si l'élément est un Article ou un Variant
            if ($item->wishlistable instanceof Article) {
                $article = $item->wishlistable;
                // Utiliser le prix promotionnel s'il existe, sinon le prix standard
                $price = $article->discounted_price ? (float) $article->discounted_price : $article->price;
            } elseif ($item->wishlistable instanceof Variant) {
                $variant = $item->wishlistable;
                // Utiliser le prix promotionnel s'il existe, sinon le prix standard
                $price = $variant->discounted_price ? (float) $variant->discounted_price : $variant->price;
            } else {
                // Passer les autres types d'éléments si nécessaires
                continue;
            }

            // Ajouter le prix de l'article ou de la variante au montant total
            $totalAmount += $price * $item->quantity;
        }

        // Retourner le montant total formaté
        return number_format($totalAmount, 2, ',', ' ');
    }

    public function createQuoteFromWishlist()
    {
        // Utiliser une transaction pour s'assurer que toutes les opérations se passent correctement
        return DB::transaction(function () {

            $user = $this->user;

            // Créer une nouvelle commande
            $quote = Quote::create([
                'user_id' => $user->id,
                'status_id' => 4
            ]);

            // Ajouter les items de la wishlist dans la commande
            foreach ($this->items as $wishlistItem) {
                $quote->items()->create([
                    'quoteable_id' => $wishlistItem->wishlistable_id,
                    'quoteable_type' => $wishlistItem->wishlistable_type,
                    'quantity' => $wishlistItem->quantity,
                ]);
            }

            // Vider la wishlist après création de la commande
            $this->items()->delete();

            // Retourner la commande créée
            return $quote;

        });
    }
}
